In [101]:
# Content retrieval ordered by how many times a specific word is mentioned in the content of the text. 
# Returns top 3 medical conditions with the most mentions of the searched up word in the content.
import pandas as pd
import re
def search_conditions(query):
    df = pd.read_csv("/Users/timmyg/Downloads/illness.csv")
    df = df.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)
    pd.set_option('display.max_colwidth', 1000) 
    query = query.lower()
    results = df[df["Content"].str.contains(query, case=False, na=False)]
    df_sorted = results[["Title", "Content"]]
    df_sorted["Content"].str.count(query)
    df_sorted_real = df_sorted.sort_values('Content', ascending=False).reset_index(drop=True)
    # lowkey had no clue how to do the snippets part so this is from gpt..if anyone has any mods that would be great!
    def extract_snippet(text):
        matches = re.findall(fr'(?i).{{0,200}}\b{query}\b.{{0,200}}', text)
        if matches:
            return " ... ".join(m.strip() for m in matches)
        else:
            return ""
    df_sorted_real["Search Relevant Content"] = df_sorted_real["Content"].apply(extract_snippet)
    return df_sorted_real.head(3)

search_conditions("headache")

,Title,Content,Search Relevant Content
0,migraine headache,"migraine is an episodic primary headache disorder. symptoms typically last 4 to 72 hours and may be severe. pain is often unilateral, throbbing, worse with exertion, and accompanied by symptoms such as nausea and sensitivity to light, sound, or odors. auras occur in about 25% of patients, usually just before but sometimes after the headache. diagnosis is clinical. treatment is with triptans, dihydroergotamine, antiemetics, and analgesics. preventive regimens include lifestyle modifications (eg, sleep habits or diet) and medications (eg, beta-blockers, amitriptyline, topiramate, divalproex, monoclonal antibodies).","migraine is an episodic primary headache disorder. symptoms typically last 4 to 72 hours and may be severe. pain is often unilateral, throbbing, worse with exertion, and accompanied by symptoms such as nausea and sensitivity to light, sound ... , or odors. auras occur in about 25% of patients, usually just before but sometimes after the headache. diagnosis is clinical. treatment is with triptans, dihydroergotamine, antiemetics, and analgesics. preventive regimens include lifestyle modifications (eg, sleep habits or diet) and medications (eg,"
1,flu,"influenza is a viral respiratory infection causing fever, coryza, cough, headache, and malaise. mortality is possible during seasonal epidemics, particularly among high-risk patients (eg, those who are institutionalized, at the extremes of age, have cardiopulmonary insufficiency, or are in late pregnancy); during pandemics, even healthy, young patients may die. diagnosis is usually clinical and depends on local epidemiologic patterns. antiviral treatment reduces the duration of illness by about 1 day and should be specifically considered for high-risk or severely ill patients. the influenza vaccine should be given annually to all eligible patients who do not have a contraindication","influenza is a viral respiratory infection causing fever, coryza, cough, headache, and malaise. mortality is possible during seasonal epidemics, particularly among high-risk patients (eg, those who are institutionalized, at the extremes of age, have cardiopulmonary insufficiency,"

In [82]:
# Alternatively, if the title contains the content searched up it's returned in this function.
import pandas as pd
def search_conditions(query):
    df = pd.read_csv("/Users/timmyg/Downloads/illness.csv")
    df = df.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)
    pd.set_option('display.max_colwidth', 1000) 
    query = query.lower()
    results = df[df["Title"].str.contains(query, case=False, na=False)]
    return results[["Title", "Content"]]

search_conditions("Flu")

,Title,Content
1,flu,"influenza is a viral respiratory infection causing fever, coryza, cough, headache, and malaise. mortality is possible during seasonal epidemics, particularly among high-risk patients (eg, those who are institutionalized, at the extremes of age, have cardiopulmonary insufficiency, or are in late pregnancy); during pandemics, even healthy, young patients may die. diagnosis is usually clinical and depends on local epidemiologic patterns. antiviral treatment reduces the duration of illness by about 1 day and should be specifically considered for high-risk or severely ill patients. the influenza vaccine should be given annually to all eligible patients who do not have a contraindication"

In [2]:
# All relevant content associated with source
import pandas as pd
def search_conditions(query):
    df = pd.read_csv("/Users/timmyg/Downloads/illness.csv")
    pd.set_option('display.max_colwidth', 1000) 
    query = query.lower()
    results = df[df["Source"].str.contains(query, case=False, na=False)]
    return results[["Title", "Content"]]

search_conditions("MSD")

,Title,Content
1,Flu,"Influenza is a viral respiratory infection causing fever, coryza, cough, headache, and malaise. Mortality is possible during seasonal epidemics, particularly among high-risk patients (eg, those who are institutionalized, at the extremes of age, have cardiopulmonary insufficiency, or are in late pregnancy); during pandemics, even healthy, young patients may die. Diagnosis is usually clinical and depends on local epidemiologic patterns. Antiviral treatment reduces the duration of illness by about 1 day and should be specifically considered for high-risk or severely ill patients. The influenza vaccine should be given annually to all eligible patients who do not have a contraindication"
2,Fever,"Fever is an elevated body temperature that occurs when the body's thermostat (located in the hypothalamus) resets at a higher temperature, primarily in response to an infection. Elevated body temperature that is not caused by a resetting of the temperature set point is called hyperthermia."
3,Migraine Headache,"Migraine is an episodic primary headache disorder. Symptoms typically last 4 to 72 hours and may be severe. Pain is often unilateral, throbbing, worse with exertion, and accompanied by symptoms such as nausea and sensitivity to light, sound, or odors. Auras occur in about 25% of patients, usually just before but sometimes after the headache. Diagnosis is clinical. Treatment is with triptans, dihydroergotamine, antiemetics, and analgesics. Preventive regimens include lifestyle modifications (eg, sleep habits or diet) and medications (eg, beta-blockers, amitriptyline, topiramate, divalproex, monoclonal antibodies)."
4,Nausea and Vomitting,"Nausea, the unpleasant feeling of needing to vomit, represents awareness of afferent stimuli (including increased parasympathetic tone) to the medullary vomiting center. Vomiting is the forceful expulsion of gastric contents caused by involuntary contraction of the abdominal musculature when the gastric fundus and lower esophageal sphincter are relaxed."

In [3]:
# What title based on symptoms
import pandas as pd
def search_conditions(query):
    df = pd.read_csv("/Users/timmyg/Downloads/illness.csv")
    pd.set_option('display.max_colwidth', 1000) 
    query = query.lower()
    results = df[df["Content"].str.contains(query, case=False, na=False)]
    return results[["Source", "Title"]]

search_conditions("pain")

  Source              Title
3    MSD  Migraine Headache